#!/bin/bash

{
  sleep 60
  while [ true ]; do
    echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ") Peers: $(wlncli listpeers | jq -cr '.peers | map(.address)')"
    SYNC_ED=$(wlncli getinfo | jq '.synced_to_chain')
    PEER_COUNT=$(wlncli listpeers | jq '.peers | length')
    if [[ ${PEER_COUNT} -lt "2" && ${SYNC_ED} == 'true' ]]; then
      echo "Attempting to reconnect"
      {
        if [[ ${CHAIN_NETWORK_CLASS} == "testnet" ]]; then
          wlncli connect --perm 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134@34.250.234.192:9735 # endurance
          wlncli connect --perm 02d2ccdf98507238b7980c94616815ad2fec75f048caeaba738f408da363e43ba1@71.14.230.82:9735 # MyCryptoGuru_LN1
          wlncli connect --perm 0298d0c6987e2e64451c7f723e15aff4dfca92f0e3973d214e206257abb0d1dd55@lnd.bitrefill.com:9735 # bitrefill
        fi

        wlncli describegraph | jq -r '.nodes | map(select(.addresses[0])) | map({connect: (.pub_key + "@" + .addresses[0].addr)}) | map(.connect) | .[]' | head -10 | xargs -n 1 wlncli connect --perm
      } > /dev/null
    fi

    sleep 300
  done
} | tee ${LND_HOME}/logs/${CHAIN_NETWORK_NAME}/bitcoin/peer.log > /dev/null
